name: build docs for DemazureOperators

on:
    push:

jobs:
    build:
        name: build docs
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: install elan
              run: |
                set -o pipefail
                curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
                ~/.elan/bin/lean --version
                echo "$HOME/.elan/bin" >> $GITHUB_PATH

            - name: build with lake
              run: lake build DemazureOperators